project:
  type: website

website:
  title: "IRT"
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Folien"
        href: slides/index.qmd
      - text: "Übungen"
        href: exercises/index.qmd
format:
  html:
    theme: flatly
    scss: styles.scss
    toc: true
