project:
  type: website

website:
  title: "IRT"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Folien"
        href: slides/index.qmd
        contents:
          - slides/1-IntroR.qmd
      - section: "Übungen"
        href: exercises/index.qmd
        contents: 
          - exercises/3-GLM.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto