project:
  type: website

website:
  title: "IRT"
  navbar:
    background: primary
    search: true
    left:
      - text: "Folien"
        href: slides/index.qmd
      - text: "Übungen"
        href: exercises/index.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto
  echo: false
