project:
  type: website

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - slides/1-IntroR.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
