project:
  type: website

website:
  title: "IRT"
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Folien"
        href: slides/index.qmd
      - text: "Übungen"
        href: exercises/index.qmd
format:
  html:
    theme: flatly
    toc: true

  letterbox-revealjs:
    embed-resources: true
    theme: styles.scss

code-link: true
code-line-numbers: false
execute:
  echo: true
highlight-style: dark.theme
callout-appearance: simple
lang: de
