---
title: "IRT Workshop"
format: html
---
```{r setup, include=FALSE}
library(rmarkdown)
```

### Tag 1

| Zeit                | Thema                                      | Beschreibung                                                                                                                                                       |
|---------------------|--------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 10:00 – 13:00       | Einführung in Modellierung latenter Variablen | Theoretische Einführung in die Modellierung latenter Variablen in Klassischer Testtheorie und Item Response Theory (IRT) (90 min.; SW)                             |
| 11:30 – 13:00       | Einführung in R                            | Einführung in die R-Programmierumgebung. Datenaufbereitung für IRT-Analysen. (90 min.; NH)                                                                         |
| 14:00 – 17:00       | IRT-Modelle in TAM                         | Übung: einfacher IRT-Modelle in TAM. Theoretische Unterscheidung zwischen `JML`, `CML` und `MML` (SW).                                                             |
| 14:00 – 17:00       | Raschmodell und GLMM                       | Theoretische Einführung und praktische Illustration: Das Raschmodell als eine Spezialfall des Allgemeinen Linearen Gemischten Modells (GLMM) (NH + SW).            |
| 14:00 – 17:00       | Reliabilität und Validität                 | Reliabilität, Validität, lokale stochastische Unabhängigkeit                                                                                                       |

: Programm 1 {.striped tbl-colwidths="[20, 30, 50]"}

### Tag 2

| Zeit                | Thema                                      | Beschreibung                                                                                                                                                       |
|---------------------|--------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 09:00 – 12:00       | Linking und Differential Item Functioning  | Verlinkte Items, lokale stochastische Unabhängigkeit, Messinvarianz (90 min.; NH)                                                                                  |
| 09:00 – 12:00       | Bedeutung von Testdesigns                  | Die Bedeutung von Testdesigns. Was kann schiefgehen, wenn Testdesigns ungeeignet sind? (SW)                                                                        |
| 13:00 – 16:00       | Höher parametrisierte Modelle              | Höher parametrisierte Modelle: 2pl, 3pl, partial credit (NH)                                                                                                       |
| 13:00 – 16:00       | Längsschnittliche Designs                  | Längsschnittliche Designs: Wiederholte Messungen für Individuen, Kohorten oder Populationen (SW)     
|
: Programm 1 {.striped tbl-colwidths="[20, 30, 50]"}

### Tag 3

| Zeit                | Thema                                      | Beschreibung                                                                                                                                                       |
|---------------------|--------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 09:00 – 12:00       | Praktische Überlegungen                    | Praktische Überlegungen: Welches Modell für welche Forschungsfrage? Wieviele Personen sind notwendig für welches Forschungsdesign? Theoretische Überlegungen und praktische Empfehlungen (180 min., SW + NH) |
| 13:00 – 16:00       | Das ganze Bild                             | Vollständige “Schritt für Schritt”-Analyse von Forschungsdaten: Datenaufbereitung, Kalibrierung, Plausibilitätsprüfungen, Messinvarianz, Beantworten von Forschungsfragen (180 Min., SW/NH) |


: Programm 3 {.striped tbl-colwidths="[20, 30, 50]"}
