---
title: "IRT Vorraussetzungen"
author: "Nicklas Hafiz"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: revealjs
---

# Einführung
Damit wir von den ganzen Vorteilen der Item Response Theory profitieren können, müssen einige Annahmen erfüllt sein. 

- Eindimmensionalität
- lokalen stochastischen Unabhänigkeit (https://files.eric.ed.gov/fulltext/EJ1224232.pdf). 

## Lokal stochastische Unabhängigkeit
Nach Kontrolle für die Personenfähigkeit korrelieren die Items nicht mehr. Der einzige Grund dafür, dass die Items zusammenhängen, ist also, dass die Antwort von diesem Konstrukt beeinflusst wird. 
Durch die Kontrolle für die Personenfähigkeit halten wir also den Fähigkeitswert konstant (alle Personen haben die gleiche Fähigkeit), 

- Abbildung
- Einordnung: Lokale Unabhängigkeit, weitere Begriffe?
- Beispiel

## Linking

https://hectornajera83.github.io/book/scale-equating-and-linking.html

- Tolle Eigenschaft von IRT: Personen müssen nicht den exakt gleichen Test bearbeiten, um miteinander verglichen zu werden.   
Ein Subset von Items ist ausreichend. 
- Mit Hilfe dieser **Ankeritems** können wir die Schwierigkeiten der Items auf die gemeinsame logit Skala bringen. 


## Messinvarianz


## Beispiel was bei nichtbeachtung passiert