---
title: "3) Das Raschmodell als eine Spezialfall des Allgemeinen Linearen Gemischten Modells"
author: "Nicklas Hafiz"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: revealjs
---


# Einführung

## Überblick
In dieser Session wollen wir uns mit dem Raschmodell als Spezialfall des Allgemeinen Linearen Gemischten Modells (GLMM) beschäftigen.  Dafür werden zunächst eine kleine Einführung/Wiederholung zu gemischten Modellen machen und uns dabei spannende Daten anschauen. 

Possible example data: Academic motivation scale (https://bookdown.org/bean_jerry/using_r_for_social_work_research/item-response-theory.html)

## GLM

# Gemischte Modelle (Linear Mixed Models)

Grafik mit level-Struktur

## Einführungsbeispiel

https://www.bristol.ac.uk/cmm/learning/support/datasets/

- Intro example: Something with schools (fitting to rasch context)
- Simple Exercise: Simulate multilevel data (with some help, so it goes quicker)

# Umgang mit genesteten Daten

## Option 1: Ignorieren
Generell eher keine gute Idee:

Wir tuen so, als ob wir mehr Informationen hätten, als wir letztendlich haben. Das liegt daran, dass Abhängigkeiten zwischen den Daten bestehen. Konsequenz:

- Standardfehler werden unterschätzt, unsere Inferenzstatistischen Tests werden eher signifikant. 

Außerdem kann die genestete Struktur von Interesse sein!

## Option 2: Aggregieren auf Gruppenebene

# Gleichungen
## Level 1 Gleichung

Für jede Gruppe j:
$$
y_{ij} = \beta_{0j} + \beta_{1j}x_{ij} + e_{ij}
$$

Abbildung

## Level-2 Gleichung

$$
\beta_{0j} = \beta_{0}+\zeta_{0j}
$$

$$
\beta_{1j} = \beta_1 + \zeta_{1j}
$$

Abbildung

## Das gemischte Modell
Jetzt müssen wir nur noch einsetzen:


$$
y_{ij} = \beta_{0j} + \beta_{1j}x_{ij} + e_{ij}
$$
$$
\beta_{0j} = \beta_{0}+\zeta_{0j}
$$

$$
\beta_{1j} = \beta_1 + \zeta_{1j}
$$

$$
y_{ij} = \beta_{0}+\beta_1x_{ij} + \zeta_{0j} + \zeta_{1j}x_{ij} + e_{ij}
$$


## Simulation
In der folgenden Übung wollen wir uns Daten mit einer genesteten Struktur simulieren. 

https://ademos.people.uic.edu/Chapter16.html


## Was sind random, was fixed effects?

:::: {.columns}

::: {.column width="50%"}
**Random Effects**

- Wir nehmen einen zugrundeliegenden Gesamtmittelwert an, von dem die Gruppen **random** abweichen. Anders ausgedrückt: Wir nehmen an, dass die Gruppen aus einer Grundverteilung gezogen wurden. Wir hätten theoretisch aber auch andere Gruppen ziehen können: Wenn wir das Experiment wiederholen, die level auf diesem Faktor werden andere sein.
- Dann sollten wir partial pooling nutzen:



- Dadurch können wir Informationen aus den Anderen Gruppen ebenfalls nutzen. 


:::


::: {.column width="50%"}
**Fixed Effects**

- Hier machen wir diese Annahme einfach nicht. Wir sind also an den tatsächlichen Gruppen interessiert, die wir untersuchen, und möchten nicht davon ausgehen, dass wir theoretisch auch andere Gruppen hätten ziehen können.

:::


::::

## Beispiel

Wir untersuchen den Erfolg von Verhaltenstherapie und Psychoanalyse anhand der Rückfallquote nach einem Jahr.  
Patient*innen müssen hier nach Therapeut*innen genested werden. Dabei können wir die Therapeut*innen als random effects betrachten, wir haben sie ja schließlich nur als Mittel zum Zweck aus der Population an Therapeut*innen gezogen. Die Behandlungsform (Verhaltenstherapie, Psychoanalyse) ist hingegen ein fixed effect, da wir nur diese beiden Behandlungsformen untersuchen wollen.

Anders würde das Ganze aussehen, wenn uns die Erfolgsquote speziell dieser Therapeut*innen interessieren würde. Dann könnten wir sie ebenfalls als fixed effect im Modell mit aufnehmen. 





# Raschmodell als LMM
Warum das Ganze? Es geht doch eigentlich um IRT?

## Raschmodell als Spezialfall für LMM
Wir können das Raschmodell als Spezialfall des LMMs betrachten:


::: aside
- De Boeck and Wilson (2004)
- Doran et al. (2007)
:::



## Fixed und Random Effects

- Entwicklung Fragebogen um diesen an verschiedenen Stichproben zu nutzen: Person als random, Items als fixed
- Entwicklung von Items für einen großen Fragenkatalog: Items ebenfalls als random


## Beispiel

```{r}
library(lme4)

```

## Exercise
Fit a Rasch Model using TAM and compare!


